fix(vault): check vault before checking providers
Because of the new providers hookers, a use of the proviers class was
perform before checking if Vault was enabled. And if Vault was not
enabled there was a `NoClassDefFoundError`.
Now a first Vault check is done before the use of the providers class.